<a href="https://colab.research.google.com/github/ridhampatel14/ML_projects/blob/main/sentiment_analysis_final_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The data is about the student reviews of each classes taken by different professors in CSE.
This project contains preprocessing of the data, Translation of language using google translate and sentiment analysis of the reviews given by the students using NLTk and NRCLex libraries.**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
#libraries needed for preprocessing 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("/content/drive/MyDrive/Sem-7 Student's feedback (Responses).csv")
df

,Timestamp,Subject Name,Teacher Name,Date,mark your sentiment(s) after this lecture (Following image of sentiments can be used as reference),Submit your comments about lecture / content delivery/ presentation/ teacher etc here. લેક્ચર/ પ્રેઝન્ટેશન/ શિક્ષક વગેરે. વિષેના તમારા મન્તવ્યો અહીં લખો,Name,University/ college name (Short name also accepted)
0,6-29-2021 12:14:04,DS,Viral panchal,29-06-2021,Bored,Bas content dekh ke wahi repeat krte h.. no ex...,NaN,NaN
1,6-29-2021 12:16:12,Distributed systems,Viral Panchal,29-06-2021,Happy,Good.,Harsh Maisuriya,NaN
2,6-29-2021 12:38:46,Distributed system,Viral panchal,29-06-2021,Happy,Very good,Dangrosiya Shyam J,NaN
3,6-29-2021 12:49:11,Natural Language Processing,Professor Unnati shah,29-06-2021,Happy,The subject is really interesting and the teac...,Het Patel,NaN
4,6-29-2021 12:50:24,NLP,Ms. Unnati Shah,29-06-2021,Happy,ઘણું સારું explanation છે so I can understand...,Moksha Dikshit,NaN
...,...,...,...,...,...,...,...,...
474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head(10)

,Timestamp,Subject Name,Teacher Name,Date,mark your sentiment(s) after this lecture (Following image of sentiments can be used as reference),Submit your comments about lecture / content delivery/ presentation/ teacher etc here. લેક્ચર/ પ્રેઝન્ટેશન/ શિક્ષક વગેરે. વિષેના તમારા મન્તવ્યો અહીં લખો,Name,University/ college name (Short name also accepted)
0,6-29-2021 12:14:04,DS,Viral panchal,29-06-2021,Bored,Bas content dekh ke wahi repeat krte h.. no ex...,NaN,NaN
1,6-29-2021 12:16:12,Distributed systems,Viral Panchal,29-06-2021,Happy,Good.,Harsh Maisuriya,NaN
2,6-29-2021 12:38:46,Distributed system,Viral panchal,29-06-2021,Happy,Very good,Dangrosiya Shyam J,NaN
3,6-29-2021 12:49:11,Natural Language Processing,Professor Unnati shah,29-06-2021,Happy,The subject is really interesting and the teac...,Het Patel,NaN
4,6-29-2021 12:50:24,NLP,Ms. Unnati Shah,29-06-2021,Happy,ઘણું સારું explanation છે so I can understand...,Moksha Dikshit,NaN
5,6-29-2021 12:51:55,Natural language Processing,Prof. Unnati Shah,29-06-2021,Excited,In today's lecture our lecturer explained us h...,Harsh Patel,NaN
6,6-29-2021 12:52:11,Natural Language Processing,Unnati Shah,29-06-2021,Excited,Today's lecture was really interesting as we g...,NaN,NaN
7,6-29-2021 12:53:23,natural language processing,unnati shah,29-06-2021,Happy,NLP is a intresting subject and our factulty i...,NaN,NaN
8,6-29-2021 12:54:08,Nactural language process,Unnati shah,29-06-2021,Happy,Presentation is very good and topic is also nice,Nakrani sagar sureshbhai,NaN
9,6-29-2021 12:55:11,Natural Language Processing,Unnati Ma'am,29-06-2021,Happy,Lectures are very interesting and interactive ...,Dhruv Parimalbhai Patel,NaN

In [5]:
df=df.rename(columns={'mark your sentiment(s) after this lecture (Following image of sentiments can be used as reference)': 'sentiments', 'Submit your comments about lecture / content delivery/ presentation/ teacher etc here.  લેક્ચર/ પ્રેઝન્ટેશન/ શિક્ષક વગેરે. વિષેના તમારા મન્તવ્યો અહીં લખો': 'comments',"Subject Name":"Subject_Name"})

In [7]:
df1=df[["Subject_Name","Date","sentiments","comments"]]
df1

,Subject_Name,Date,sentiments,comments
0,DS,29-06-2021,Bored,Bas content dekh ke wahi repeat krte h.. no ex...
1,Distributed systems,29-06-2021,Happy,Good.
2,Distributed system,29-06-2021,Happy,Very good
3,Natural Language Processing,29-06-2021,Happy,The subject is really interesting and the teac...
4,NLP,29-06-2021,Happy,ઘણું સારું explanation છે so I can understand...
...,...,...,...,...
474,NaN,NaN,NaN,NaN
475,NaN,NaN,NaN,NaN
476,NaN,NaN,NaN,NaN
477,NaN,NaN,NaN,NaN
478,NaN,NaN,NaN,NaN

In [8]:
#first remove duplicate rows 
df1=df1.drop_duplicates(subset=['sentiments', 'comments'])
df1

,Subject_Name,Date,sentiments,comments
0,DS,29-06-2021,Bored,Bas content dekh ke wahi repeat krte h.. no ex...
1,Distributed systems,29-06-2021,Happy,Good.
2,Distributed system,29-06-2021,Happy,Very good
3,Natural Language Processing,29-06-2021,Happy,The subject is really interesting and the teac...
4,NLP,29-06-2021,Happy,ઘણું સારું explanation છે so I can understand...
...,...,...,...,...
375,ML,27-07-2021,Excited,Today offline lec bhariyu and all doubt clear ...
376,ML,27-07-2021,Excited,Today we attend offline lecture so we probably...
377,Ml,27-07-2021,"Happy, Excited",Today i attended offline lecture and i am bet...
378,Dynamic of machinery,04-08-2021,Happy,Na
379,NaN,NaN,NaN,NaN

In [9]:
#dropping null values 
#as here there can be no any alternative values so we can not fill null values so have to drop null values row wise
df1=df1.dropna(axis=0)
df1

,Subject_Name,Date,sentiments,comments
0,DS,29-06-2021,Bored,Bas content dekh ke wahi repeat krte h.. no ex...
1,Distributed systems,29-06-2021,Happy,Good.
2,Distributed system,29-06-2021,Happy,Very good
3,Natural Language Processing,29-06-2021,Happy,The subject is really interesting and the teac...
4,NLP,29-06-2021,Happy,ઘણું સારું explanation છે so I can understand...
...,...,...,...,...
374,ML,27-07-2021,Excited,"actually , clear everything...thank you. your ..."
375,ML,27-07-2021,Excited,Today offline lec bhariyu and all doubt clear ...
376,ML,27-07-2021,Excited,Today we attend offline lecture so we probably...
377,Ml,27-07-2021,"Happy, Excited",Today i attended offline lecture and i am bet...
378,Dynamic of machinery,04-08-2021,Happy,Na

In [11]:
#need to convert all the data into lower case for case sensitivity
for col in df1.columns:
    df1[col] = df1[col].str.lower()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [12]:
df1

,Subject_Name,Date,sentiments,comments
0,ds,29-06-2021,bored,bas content dekh ke wahi repeat krte h.. no ex...
1,distributed systems,29-06-2021,happy,good.
2,distributed system,29-06-2021,happy,very good
3,natural language processing,29-06-2021,happy,the subject is really interesting and the teac...
4,nlp,29-06-2021,happy,ઘણું સારું explanation છે so i can understand...
...,...,...,...,...
374,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
375,ml,27-07-2021,excited,today offline lec bhariyu and all doubt clear ...
376,ml,27-07-2021,excited,today we attend offline lecture so we probably...
377,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
378,dynamic of machinery,04-08-2021,happy,na

In [13]:
#data consist of many different names for one values as ml and machine learning and machine-learning so need to make it consistent
lst=df1.Subject_Name.unique()
lst

array(['ds ', 'distributed systems', 'distributed system',
       'natural language processing', 'nlp', 'nactural language process',
       'application development', 'compiler design',
       'natural language processing ', 'is', 'cd', 'ml', 'ai ', 'ds',
       'ai', 'machine learning', 'machine learning ', 'krunal rakholiya',
       'mcwc', 'machine learning (ml)', 'mi', 'compiler design(3170701)',
       'mobile application development', 'big data analytics',
       'information security', 'mad', 'dme', 'bda',
       'design of machine elements', 'is ', 'digital forensics', 'dbms ',
       'information retrieval', 'artificial intelligence',
       'information security(3170720)', 'design of machine and element',
       'gamit alka alubhai', 'artificial intelligence (ai)', 'dmae',
       'ice ', 'software engineering ', 'software engineering',
       'computer network', 'computer vision', 'ukani hemanshi sanjaybhai',
       'se', 'analysis and design of algorithms',
       'each and every subject', 'pds', 'ada', 'python for data science',
       'mad (mobile development)', 'ml ', 'ml (machine learning',
       'ds (distributed system)', 'compiler design (cd)',
       'mobile application and development',
       'mobile computing and wireless communication', 'cv', 'cd ',
       'cd lab ', 'applied machine learning', 'cd lab', 'dme ', 'ai lab',
       'ppe', 'complier design', 'sanket maisuriya ',
       'dynamic of machinery'], dtype=object)

In [14]:
ls=[]
for i in df1["Subject_Name"]:
  if(i=="analysis and design of algorithms"or i=="bda" or i=="ada"):
    ls.append("ada")
  elif(i=="ai " or i=="ai lab" or i=="artificial intelligence" or i=="artificial intelligence (ai)"):
    ls.append("ai")
  elif(i=="information security" or i=="information security(3170720)" or i=="is "):
    ls.append("is")
  elif(i=="ds (distributed system)" or i=="distributed systems" or i=="distributed system" or i=="ds "):
    ls.append("ds")
  elif(i=="applied machine learning" or i=="machine learning " or i=="mi" or i=="machine learning" or i=="machine learning (ml)" or i=="ml " or i=="ml (machine learning"  ):
    ls.append("ml")
  elif(i=="cd" or i=="compiler design" or i=="cd lab" or i=="compiler design (cd)" or i=="cd " or i=="complier design" or i=="cd lab " or i=="compiler design(3170701)" ):
    ls.append("cd")
  elif(i=="natural language processing " or i=="nactural language process" or i=="natural language processing"):
    ls.append("nlp")
  elif(i=="mobile computing and wireless communication" ):
    ls.append("mcwc")
  elif(i=="mobile application and development" or i=="mobile application development" or i=="application development" or i=="mad (mobile development)"):
    ls.append("mad")
  elif(i=="big data analytics"):
    ls.append("bda")
  elif(i=="computer vision"):
    ls.append("cv")
  elif(i=="software engineering" or i=="software engineering "):
    ls.append("se")
  elif(i=="information retrieval" or i=="is"):
    ls.append("ir")
  elif(i=="computer network" ):
    ls.append("cn")
  elif(i=="design of machine and element" or i=="design of machine elements" or i=="dme " or i=="dmae"):
    ls.append("dme")
  elif(i=="python for data science"):
    ls.append("pds")
  elif(i=="dynamic of machinery"):
    ls.append("dom")
  elif(i=="digital forensics"):
    ls.append("df")
  
  
  else:
    ls.append(i)

In [15]:
l=set(ls)
l=list(l)
print(l)

['dom', 'ai', 'dme', 'ukani hemanshi sanjaybhai', 'is', 'krunal rakholiya', 'ds', 'gamit alka alubhai', 'ir', 'pds', 'sanket maisuriya ', 'se', 'cv', 'mcwc', 'cn', 'ml', 'mad', 'cd', 'nlp', 'dbms ', 'each and every subject', 'bda', 'ppe', 'ada', 'ice ', 'df']

In [16]:
print(len(ls))

338

In [17]:
df1["Subject_Name"]=ls

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [18]:
df1

,Subject_Name,Date,sentiments,comments
0,ds,29-06-2021,bored,bas content dekh ke wahi repeat krte h.. no ex...
1,ds,29-06-2021,happy,good.
2,ds,29-06-2021,happy,very good
3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,nlp,29-06-2021,happy,ઘણું સારું explanation છે so i can understand...
...,...,...,...,...
374,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
375,ml,27-07-2021,excited,today offline lec bhariyu and all doubt clear ...
376,ml,27-07-2021,excited,today we attend offline lecture so we probably...
377,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
378,dom,04-08-2021,happy,na

In [19]:
lst=df1.Subject_Name.unique()
lst

array(['ds', 'nlp', 'mad', 'cd', 'ir', 'ml', 'ai', 'krunal rakholiya',
       'mcwc', 'bda', 'is', 'dme', 'ada', 'df', 'dbms ',
       'gamit alka alubhai', 'ice ', 'se', 'cn', 'cv',
       'ukani hemanshi sanjaybhai', 'each and every subject', 'pds',
       'ppe', 'sanket maisuriya ', 'dom'], dtype=object)

In [20]:
indexs = df1[df1['Subject_Name'].map(len) > 5].index
indexs

Int64Index([29, 52, 100, 108, 128, 138, 356], dtype='int64')

In [21]:
df1.drop(indexs, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [22]:
lst=df1.Subject_Name.unique()
lst

array(['ds', 'nlp', 'mad', 'cd', 'ir', 'ml', 'ai', 'mcwc', 'bda', 'is',
       'dme', 'ada', 'df', 'dbms ', 'ice ', 'se', 'cn', 'cv', 'pds',
       'ppe', 'dom'], dtype=object)

In [23]:
#removing duplicate values based on 
df1=df1.drop_duplicates(subset=['Date','sentiments', 'comments'])
df1

,Subject_Name,Date,sentiments,comments
0,ds,29-06-2021,bored,bas content dekh ke wahi repeat krte h.. no ex...
1,ds,29-06-2021,happy,good.
2,ds,29-06-2021,happy,very good
3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,nlp,29-06-2021,happy,ઘણું સારું explanation છે so i can understand...
...,...,...,...,...
374,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
375,ml,27-07-2021,excited,today offline lec bhariyu and all doubt clear ...
376,ml,27-07-2021,excited,today we attend offline lecture so we probably...
377,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
378,dom,04-08-2021,happy,na

In [24]:
df=pd.read_csv("/content/drive/MyDrive/preproccessed(1).csv")

In [25]:
df

,Unnamed: 0,Subject_Name,Date,sentiments,comments
0,0,ds,29-06-2021,bored,bas content dekh ke wahi repeat krte h.. no ex...
1,1,ds,29-06-2021,happy,good.
2,2,ds,29-06-2021,happy,very good
3,3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,4,nlp,29-06-2021,happy,ઘણું સારું explanation છે so i can understand ...
...,...,...,...,...,...
322,374,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
323,375,ml,27-07-2021,excited,today offline lec bhariyu and all doubt clear ...
324,376,ml,27-07-2021,excited,today we attend offline lecture so we probably...
325,377,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
326,378,dom,08-04-2021,happy,na

**translation of the comments**

In [26]:
pip install googletrans==4.0.0-rc1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: googletrans==4.0.0-rc1 in /usr/local/lib/python3.7/dist-packages (4.0.0rc1)
Requirement already satisfied: httpx==0.13.3 in /usr/local/lib/python3.7/dist-packages (from googletrans==4.0.0-rc1) (0.13.3)
Requirement already satisfied: rfc3986<2,>=1.3 in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2022.6.15)
Requirement already satisfied: hstspreload in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2022.9.1)
Requirement already satisfied: httpcore==0.9.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.1)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.7/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.0)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.7/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: h11<0.10,>=0.8 in /usr/local/lib/python3.7/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.0)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.7/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.7/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)

In [27]:
from googletrans import Translator

In [28]:
translator = Translator()

In [29]:
ls=df["comments"].tolist()
len(ls)

327

In [30]:
lst=[]
for i in range(100):
  temp=translator.translate(ls[i], dest='en')
  lst.append(temp.text)

In [31]:
len(lst)

100

In [32]:
for i in range(100,200):
  temp=translator.translate(ls[i], dest='en')
  lst.append(temp.text)

In [33]:
len(lst)

200

In [34]:
for i in range(200,300):
  temp=translator.translate(ls[i], dest='en')
  lst.append(temp.text)

In [35]:
len(lst)

300

In [36]:
for i in range(300,327):
  temp=translator.translate(ls[i], dest='en')
  lst.append(temp.text)

In [37]:
len(lst)

327

In [38]:
lst

['Just see the content and repeat the same .. No Examination .. Written Reading Book',
 'good.',
 'very good',
 'the subject is really interesting and the teacher is doing a great job teaching it.',
 'Very good Explanation is so I can understand in very well manner.',
 "in today's lecture our lecturer explained us how nlp can help us and how it can automate some tasks, that makes me excited to learn more about nlp subject.",
 "today's lecture was really interesting as we got to learn new things. and i'm really excited for the next lecture for this activity.",
 'nlp is a interesting subject and our faculty is very good',
 'presentation is very good and topic is also nice',
 'lectures are very interesting and interactive as well.',
 'explanation is very good  \nsubject topic is very interesting  and useful in future',
 'the presentation was very appealing to my eyes. it was very easy to understand and very informative.',
 'after hearing the lecture and looking at the presentation slides it helped me develop a sense of understanding . and me understanding the topic made me happy.',
 'overall satisfied with the teaching methods, and the presentations are really good, however the course content comprises of a lot of outdated technologies and theories rather than newer techniques and theories.',
 'excellent content delivery.teaching method was good. good structured and interesting presentation.',
 'it was very interesting and useful lecture to know about how we encrypt and decrypt the message.',
 'extremely good',
 'extremely nice',
 'good',
 'nice teaching',
 'lecture was informative.',
 'nicely explain',
 'good',
 'wonderful 😊',
 'devarshi sir explains each and every topic very deeply nd meaning-full. sir also ask us questions about the topic and give us many more knowledge about the subject.',
 'devarshi sir explains each and every topic very deeply nd meaning-full. sir also ask us questions about the topic and give us many more knowledge about the subject.',
 'good explanation',
 'lecture ma koi difficulty avati nathi. i can understand in  very well manner.',
 "Sir's teaching trick is good ... & well covers all the topic ..",
 "it's really good and understand the all topic.",
 "ma'am nu teaching bahu j mast 6e ... I love it ... & ma'am j je topic ma khaber na pade ane 2-3 jetli var kahi a atli var varied 6e..😊",
 'Sir Nu Teaching Mast 6E ... Sir Example Aapi Ne Pan Saru Explain Kari Ne Samjave 6e So Bhanvani Maja Aave 6E ...',
 "Ma'am Pictures & PPT Through Easy Way Thi Hard Topic Samjave 6E ... & Ma'am Lakhave Pan 6e Badha Topic Nu ...",
 "ma'am nu teaching sari 6e ... Sari Rite Bhaanave 6e Maam & Concept Pan Clear Karave 6E ...",
 'Sir Saru Bhanave 6E & If Fig & All Aave to A Draw Karva Mate Time Pan Aave 6e Jenathi Exam Time Ma A Kam Lage & Sir Na Lecture Ma Majak Masti Pan Thai Atle Maja Aave ...',
 'good teaching by mam',
 'explanation is good and your lecture is interesting. but sir please share your screen. because without share screen we are not understand properly.',
 'i can understand very well.',
 'sir had explained so calmly and explanation was so good. very exited for ml',
 'sir explains all topic very well',
 'very good.. sir taught without ppt but it was understood very well..!!',
 "good explanation by ma'am",
 'always excited to learn something new. and perfect teaching and fruitful knowledge gain.',
 'i have enjoyed lecture because mam explain all the topic very well and in detail.',
 'sometime the lectures are not that interesting and are not that interactive.',
 'hemil sir is one of the best sir, that makes subject excited and my interest increases more and more and i really want to learn android application development.',
 'my fav subject . i like to learn about ai .mam is going to deeply. thank you mam!',
 'good teaching. good explanation.',
 'sir nicely introduction apiyu machine learning and difference smjaviya deep leaning and machine learning no....and ak sari rite explain kariyu with example',
 'Patta Na Througa: Well Examplayed in Detail and Assi Ladrstand',
 'no comments',
 'All points explain well.The press is good.',
 'i am happy with this lec but you need to give live world example related to topics and industry examples',
 'good teaching',
 'good i can understand very well',
 'i can really understand topics taught by her because she made it easy to understand.',
 'Topics Explain well by giving Mum Examplay',
 'very well explain each topic.',
 'Bhot explains with a top of a topic deep and in the examples.',
 'Explanation about the topics was good, but sir screen/ppt Share Karya Vagar J Bhana Ta Hata.Do If Explaination Time Pr ppt Share Kari Hoi to Understand Karva Ma Easy Pade.',
 'lectures has always been good',
 'lecture was proper, content delivery was good and presentation was also good.',
 'very good explanation of each and every topic of that subject by hemil sir and i understand it very well',
 'Bo Interesting is a suburb, so much fun.',
 'Sir A Bov Mast Explain Basic Interruption of Android and Architect & Leaf Cycle of Android.',
 'good lecture',
 'hemil sir always teaches in the way we understand',
 'Easy Hatu and Interesting Hatu so bored nayya',
 'lecture interested hato',
 'required some practical examples to understand related topics',
 'theory point of view is solid',
 'the same thing we had already learn in toc sub in previous sem,so it is bit of boring.',
 "ma'am just reads what's on the screen, kantado aave.",
 "In 'Aam Topic Explanation Bow does good, which can make the asillee understand.",
 "Today's lecture be very good. Whatever you explained is aslay and well -understood",
 "today's lec excited because there are three new topics we learned",
 'In Ami, we teach smilingly as we are studying a small one of the little one.',
 "subject piques my curiosity but ma'am nu presentation jarik lackluster lage, ok-ok.",
 "today's lecture is  more exciting and i  enjoy it. i like your teaching pattern.",
 "ma'am does not teach which ide or which software is use to design a compiler, even ma'am does not gave a demo, that's why i'm sad.",
 'sir lecture ni speed plz slow kri shako',
 'Excellent material covered in a lecture.Class interaction was observed during the lecture.\nbohot mazza aaya',
 "this subject in ma'am giving activities and explain repeatedly so understand completely",
 'its really fun learning different types of cypher.',
 "another cool subject but sir's presentation and delivery doesn't fit with how awesome the subject could potentially be.",
 'i fully enjoyed in unnati maam lectures, she explained everything in detail and it made it easier for me to understand. it is very helpful as mam asks questions in the lecture.',
 'revision of system software. so, lecture boring hato.',
 'WellIf there is a problem or a problem.After the lecture is completed to tell',
 'There is a lot of fun in this lecture but also a little boring.',
 'in this subject contents are very interesting  so ema vdhre kai new janva male ch',
 'revision of system software, etle lecture boring lagyo.',
 'teaching good',
 'presentation is understandable',
 'nice explanation and lecture is really enjoyable and the subject is really interesting.',
 'Sir Koi Disturbance Nai Hato & Doubt Pan Sari Rite clear thaya but man thodi speed hati aevu laygu baki badhu baraber hatu.😇',
 "subject is not up to my expectations. though i feel it seems boring as it has just a week i've been studying this particular subject.",
 'good',
 'There is a lot of good Explanation. None of the defects in the lecture.',
 'CD is a interested Subject & Faculty is good .. BECOUGE NOT ONLY SUBJECT RELATED KNOWLEDGE to share but many other things are known ...',
 'The same is understood.',
 'explanation is good.',
 'In Axhamplay than Topic Explain, we gave it to understand the perticular topic from what we gave.',
 'Explain well by giving a cross xemple to the team of Teaching Mathodas & Explanation',
 'very good explanation by sir,',
 'In the evening all',
 'teaching method,explanation and all good.',
 'clear and understandable presentation, good teaching method and we can feel free to ask questions & doubts.',
 'the explanation was good',
 'sari. rite. se. study. mate',
 'good explanation',
 'nicely smjaviyu and lab hour ma practical ne smjviya',
 'i found this lecture very interesting and informative. the way of explanation is very clear and to the point.',
 'i found this lecture very informative. i learned many new topics. the way of explanation is very clear.',
 'explanation is good. so i can understand very well.',
 'New Concept Janva Malyo ..... se ma shu aave e khabar padi ..... I want to know more about this subject 😀',
 'It was fun but a little bore',
 'Maja Avi Reading Ma 👍',
 'Pehla Vadhare Maja Avti Ti KM K Questions Answers Thata HTA HU ROJ NU ROJ Prepare Karine avti j hti ane ane apti hti pan baki na nai apta hta ana lidhe have badha ne avi rite bhanvanu its',
 'Maja Avi Reading Ma 👍',
 "It's fun to fill the lecture",
 'lecture was interesting but a lot of time was spend on unnecessary discussion.',
 'learned new things!!! and it was interesting',
 'The teacher does not have fun in the lake.Viva Les Viva Lace in Lake.Something similar is not understood in Lake.And keep it irritated.',
 'i like the way of teaching🤘',
 'i am very excited for this subject lecture.the method you used to teach by asking question is better.',
 'Bow has fun in the Conceptors with new algorithims',
 "Mam's Teaching Method is too good.And Mam Vacche Vacche Question Pan Puche so we have to fully focus on lecture.But Saaru Che and Maja Aave.",
 'su lkhvu aem thay.LEC MA MAJA J NO Aave.Tme j aekvar bhro to khbr pde.3',
 "Mum your lecture seems more interesting than the second sir/ mum lecture.Lectech doesn't look boring.",
 "today's lecture is overall good but somewhere i feel like im bored.",
 'Bau was fun in the lecture.',
 'This sir teaches peacefully.Neither hurry to teach peace.And even fun in lectures.',
 'starting ma bore hatu thodu after some time in interesting topic maja avi',
 "There was a little bore in the stating, after the boot it seemed interesting during team work's datiles.B was good in Coast Analysis ..",
 'I also like softway engineering and the faculty is just as long as the standard.',
 'in se lecture mam teach very well. she gave all knowledge about se. she teach all topic in detail. so i excited for attend this se lecture. but when mam ask questions i did not like this.',
 "mam's teaching method is good and i am feel happy that learn with interest.",
 "m's teaching method is good.So teaching method is good ..",
 'it was a very nice lecture , nicely explained in a very user friendly language',
 "didn't get what actually agile is.. ma'am has tried her best though..",
 'Explained from Pupt to explain to some of the boots who understand the same way as to understand.',
 'very good teaching',
 'very good',
 'Stop introducing Android',
 'was just an introduction lecture for mad',
 'sir had introduced syllabus and introduction of android app dev. very well. i had understood all the topics.',
 'Sir always ppt ma j b figure hoi weather it is import or not draw karva api dai ane lecture ma time pass thai.ane pachi koi b 1 topic vachi jai ane lecture pati jai.',
 'language sir use was too easy to understand. but sir gives little bit extra time for drawing figure or writing any content.',
 'very well explanation given by sir about syllabus and what will we learn  in this subject',
 'MAAM TAME JE KAI SMJAVO 6O E KHBR NTHI PADTI 😓😞',
 'explanation was good to understand about android app and he also explained us about practicals',
 'great',
 'no comments',
 'no comments',
 'Voice exemplus comes down ૩ A & background voice more',
 'Khali Read Kare and Pachi Translate Kare No Explanation',
 'bo fast explanation ape 6e',
 'Sir B is well done today, so it was known as Topic Numerika.',
 'all time network problem and voice is so slow',
 'very well taught by sir',
 'we faced some difficulties because of there were no ppt but mam tried to explain us and also i little bit understood about the topic also mam told that she will explain again in next lecture with ppt.. so overall it was good',
 'PPT Presentation of Hatu',
 "difficult to understand whatever she teach because i don't have any study material of this subject but she told us that she will provide study material soon",
 'overall lacture was good.',
 'lecture was good but not that much interactive.',
 'installation steps and text classification was clear.',
 'good teaching',
 'Mum Bow is well explained.\nBoots a little speed\nIf the speed is done, then the mirror will be good',
 'Understand, Revelation can also be found',
 'good explanation. practical is also explaining very well so we can understand it easily.',
 'Ach Si Society I Mum',
 'good explanation of the practical.',
 'please take attendance from participant list because today my mic is not working so my attendance is not consider',
 'explanation is good',
 'we learn about anaconda python and how to install it and run the program',
 'The press is good and there is a little understanding.',
 'but no time management',
 'I have a lot of way to teach your expansion and teaching.Please explain once again.',
 'I read very much.Your lecture this very interesting.',
 "i was trying to join at 9:45 but sir haven't allow me to join where as he was allowing others to join.",
 'honestly, lack of communication skill with students while teaching. will understand more if he will teach us in gujarati.',
 'great',
 'nice.. good teaching',
 'good',
 'mam explanation is excellent',
 'Every point is well understood.',
 'Explain is well -known boot as a camera, which is not on Fig.',
 'mam,, you have great knowledge about ml.i am happy.shukriya',
 'Everyone understood well.And thank you mam for sharing solid courses.',
 'mam very well explain about what is machine learning and teaching is also good, in addition mam  explains us with real life examples about the particular topic..',
 "Lake.In this Very Interesting Boot 'Video Show does not look like",
 'Explained and M has been well understood',
 "It was fun in today's lecture.Taught",
 "it's always a great thing to learn something new under you, happy and satisfied.",
 'Rutal Mum Explain Topic more Dipali Explanes Topic 3 times even if the topic is understood.',
 "Today's luck was Nutral",
 'mam provides so good materials and courses.',
 'presentation is too good. i can understand very well.',
 'content is easily understood and presentation is good.',
 'well explained topic',
 'teach each n every topic in deeply',
 "explaining is good but explains directly without any example so i m much bore in this lecture so i don't understand much",
 'good explaining so i easily get each and every topic',
 'no comments.',
 'content is easily understand.',
 'Mams explain with good',
 'teaches good',
 "today's lecture was good",
 'The screen of Mum was just as well',
 'Topic Is Interesting Boot Agar If there is a little more FACTway, then there will be a perfection.',
 'i am able to understand every topic properly . explanation also sounds clear and helpful to revise again easily.',
 "good lecture. took attendance and left us on time. bas khali 1-2 vakht screen freezing no issue hato, but it's technical problem so it's okay.",
 'Well explained boot May two Net Jesus caused the screen stop when there was a thorough problem.',
 'The consolidate is to be a collar',
 'Broth',
 'Our language also explains with mamchara.And it is fun to read.',
 'Mum explains that Axisily understands',
 "overall it is good but we faced some issues like that data connection loss and screen is not visible properly that's sit.",
 'good teaching by sir..!!',
 'The lecture felt a bit boring.',
 'presentation is good and content is easily understood.',
 'Bow is having fun',
 'good lecture,and very understanding subject,good faculty',
 'complete knowledgeable person ! but in teaching may be she needs to work on it ,how to teaching properly , and also mam showing new world area of information technology so thankful to her🙂.',
 "she teaches nicely...so usually i don't get bored in her lecture. and subject is a bit new to me, so trying to understand more n more.",
 'the way she teach...is brilliantly...that students can understand easily with good examples...',
 'please end lec on time',
 'content delivery is good.',
 "In 'we did this well today's topic Explain",
 'saru explanation with examples',
 'Presentation',
 "Lecture ma ma'am mast Bhaneve 6e ... example aapi ne",
 'overall lacture was good.',
 'presentation , communication all things were good.',
 'lecture was so much informative.',
 'excellent teaching as always',
 'Well explains with xemplic',
 'the way sir teach every topic is so good.sir also gave real life scenarios.',
 'good and having extra knowledge',
 'overall it was good and sir explained with so many real life examples so we can understand very well',
 'one thing is that mam waiting for others students who not join on time so there were wasting our time due to others.. but overall good teaching by mam',
 'explanation nicely apiyu ...',
 'very well time management by mam because it was lab but mam taught us both theory as well as practical',
 'sir taught good',
 'good teaching by sir but the materials are little bit confusing for me',
 'good',
 'greate',
 'great',
 'Sums Nu Esplanation Barber Nati',
 "sir give his best but it's been 1 whole year of leave complete maths to it's difficult to understand quickly at a lec time .",
 'very well teaching about the topics and also sir explained about the practicals',
 'sir explain orally about the practical aim and program so i was little bit confusing... and faced difficulties to run program',
 'sari rite explain kare che.so,i can understand very well manner.',
 'Content delivery is good.Sari rete samajave che.',
 'sir explained very well.... good teaching',
 'overall, it is nice and good teaching by mam',
 'nice',
 'interesting',
 'if it is possible then try to explain with a related example.not for every theory but in which it is possible.',
 'nice presentation.',
 'very good',
 'some more examples are needed and sir to the continue 2 hour session mind for dizzy 😵',
 'good explanation, teaching in gujarati is also helpful for understanding.',
 'Okkk!',
 'nice',
 "in a derivation and numerical , sir only read it and explain but we can't able to understand.\nso please , can we go in written mode?\nwe already suggested but sir don't apply it.",
 'Sir each point explains well .So everything falls well evening',
 'i am requesting you after completing this chapter if possible then star those chapter which includes our experiment. i am requesting you because last of the semester burden on the student is low.',
 'Very good Explanation is understanding',
 'presentation is good.',
 "again today i can't join the lacture and in last lab sir have assigned us one practical without giving any information ( how to perform it , on which platform, etc ) and after that he wasn't responding in the lacture.",
 "sir just read ppt  and don't explain ppt",
 'Reading English from Pupt seems to be what does not explain that everything is simply reading.',
 'Explanation is not right.',
 'Today, Lacture mother is understood',
 'good presentation',
 'presentation saru che .i can understand very well manner.',
 'only reading the study material. only he want to finish the syllabus. no explanation.',
 'Good in understanding.',
 'nice teaching and we completed our 1st chap',
 'lecture was too informative.',
 'sir had given good introduction on some se concepts.',
 'presentation is good. i can understand very well manner.',
 'mam given some extra information about job opportunities, internship all that.',
 'mam suggested one of the most important course for ml so i felt so happy and also explained about ml',
 'sir revised previous semester subjects because it will be applied in this subject',
 'overall good',

In [39]:
df['comments']=lst

In [40]:
df

,Unnamed: 0,Subject_Name,Date,sentiments,comments
0,0,ds,29-06-2021,bored,Just see the content and repeat the same .. No...
1,1,ds,29-06-2021,happy,good.
2,2,ds,29-06-2021,happy,very good
3,3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,4,nlp,29-06-2021,happy,Very good Explanation is so I can understand i...
...,...,...,...,...,...
322,374,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
323,375,ml,27-07-2021,excited,Today Offin Lake Bhari and Al Doubt Clear Taya...
324,376,ml,27-07-2021,excited,today we attend offline lecture so we probably...
325,377,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
326,378,dom,08-04-2021,happy,na

In [41]:
df['comments'] = df['comments'].str.lower()

In [42]:
df.drop(df.columns[0],axis=1, inplace=True)

In [43]:
df

,Subject_Name,Date,sentiments,comments
0,ds,29-06-2021,bored,just see the content and repeat the same .. no...
1,ds,29-06-2021,happy,good.
2,ds,29-06-2021,happy,very good
3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,nlp,29-06-2021,happy,very good explanation is so i can understand i...
...,...,...,...,...
322,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
323,ml,27-07-2021,excited,today offin lake bhari and al doubt clear taya...
324,ml,27-07-2021,excited,today we attend offline lecture so we probably...
325,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
326,dom,08-04-2021,happy,na

In [44]:
df.to_csv("preproccessed_and_translated.csv")



Emotion extraction from the comments with NLTK

In [45]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.7)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk) (1.1.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk) (7.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk) (4.64.0)

In [46]:
df1=pd.read_csv("/content/drive/MyDrive/preproccessed_and_translated.csv")
df1

,Unnamed: 0,Subject_Name,Date,sentiments,comments
0,0,ds,29-06-2021,bored,just do the same repeat of the content. no exp...
1,1,ds,29-06-2021,happy,good.
2,2,ds,29-06-2021,happy,very good
3,3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,4,nlp,29-06-2021,happy,very good explanation is so i can understand i...
...,...,...,...,...,...
322,322,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
323,323,ml,27-07-2021,excited,today offin lake bhariu and al doubt clear taa...
324,324,ml,27-07-2021,excited,today we attend offline lecture so we probably...
325,325,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
326,326,dom,08-04-2021,happy,on

In [47]:
df1.drop(df1.columns[0],axis=1, inplace=True)
df1

,Subject_Name,Date,sentiments,comments
0,ds,29-06-2021,bored,just do the same repeat of the content. no exp...
1,ds,29-06-2021,happy,good.
2,ds,29-06-2021,happy,very good
3,nlp,29-06-2021,happy,the subject is really interesting and the teac...
4,nlp,29-06-2021,happy,very good explanation is so i can understand i...
...,...,...,...,...
322,ml,27-07-2021,excited,"actually , clear everything...thank you. your ..."
323,ml,27-07-2021,excited,today offin lake bhariu and al doubt clear taa...
324,ml,27-07-2021,excited,today we attend offline lecture so we probably...
325,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...
326,dom,08-04-2021,happy,on

In [49]:
import nltk

In [50]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [51]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [52]:
sid = SentimentIntensityAnalyzer()

In [70]:
result_using_NLTK=[]
for i in df1['comments']:
  temp_res=sid.polarity_scores(i)
  sor_res=sorted(temp_res.items(),key=lambda x:x[1],reverse=True)
  result_using_NLTK.append(sor_res[0][0])

In [72]:
df1['analysis_using_NLTK']=result_using_NLTK

In [73]:
df1

,Subject_Name,Date,sentiments,comments,analysis_using_NLTK
0,ds,29-06-2021,bored,just do the same repeat of the content. no exp...,neu
1,ds,29-06-2021,happy,good.,pos
2,ds,29-06-2021,happy,very good,pos
3,nlp,29-06-2021,happy,the subject is really interesting and the teac...,compound
4,nlp,29-06-2021,happy,very good explanation is so i can understand i...,compound
...,...,...,...,...,...
322,ml,27-07-2021,excited,"actually , clear everything...thank you. your ...",compound
323,ml,27-07-2021,excited,today offin lake bhariu and al doubt clear taa...,neu
324,ml,27-07-2021,excited,today we attend offline lecture so we probably...,neu
325,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...,compound
326,dom,08-04-2021,happy,on,neu

In [74]:
pip install NRCLex

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: NRCLex in /usr/local/lib/python3.7/dist-packages (3.0.0)
Requirement already satisfied: textblob in /usr/local/lib/python3.7/dist-packages (from NRCLex) (0.15.3)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.7/dist-packages (from textblob->NRCLex) (3.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk>=3.1->textblob->NRCLex) (4.64.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk>=3.1->textblob->NRCLex) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk>=3.1->textblob->NRCLex) (2022.6.2)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk>=3.1->textblob->NRCLex) (7.1.2)

In [75]:
from nrclex import NRCLex

In [76]:
emotion = NRCLex("very good")

In [77]:
emotion.top_emotions
#emotion.affect_dict

[('trust', 0.2),
 ('surprise', 0.2),
 ('positive', 0.2),
 ('joy', 0.2),
 ('anticipation', 0.2)]

In [78]:
emotion.affect_list

['anticipation', 'joy', 'positive', 'surprise', 'trust']

In [79]:
ls=df1["comments"].tolist()
len(ls)

327

In [80]:
lst=[]
for i in range(327):
  emotion = NRCLex(ls[i])
  temp=emotion.affect_list
  tm=list(set(temp))
  lst.append(tm)

len(lst)

327

In [81]:
df1["analysis_using_NRCLex"]=lst

In [82]:
df1

,Subject_Name,Date,sentiments,comments,analysis_using_NLTK,analysis_using_NRCLex
0,ds,29-06-2021,bored,just do the same repeat of the content. no exp...,neu,"[trust, joy, positive]"
1,ds,29-06-2021,happy,good.,pos,"[surprise, anticipation, positive, trust, joy]"
2,ds,29-06-2021,happy,very good,pos,"[surprise, anticipation, positive, trust, joy]"
3,nlp,29-06-2021,happy,the subject is really interesting and the teac...,compound,"[trust, positive, negative]"
4,nlp,29-06-2021,happy,very good explanation is so i can understand i...,compound,"[surprise, anticipation, positive, trust, joy]"
...,...,...,...,...,...,...
322,ml,27-07-2021,excited,"actually , clear everything...thank you. your ...",compound,[]
323,ml,27-07-2021,excited,today offin lake bhariu and al doubt clear taa...,neu,"[trust, fear, sadness, negative]"
324,ml,27-07-2021,excited,today we attend offline lecture so we probably...,neu,"[anticipation, joy, positive, trust]"
325,ml,27-07-2021,"happy, excited",today i attended offline lecture and i am bet...,compound,"[surprise, anticipation, positive, trust, joy]"
326,dom,08-04-2021,happy,on,neu,[]